apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: iw4s5x0du-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:a32ca1ef85166a86d9f19d325d308eac4fd86524@sha256:c3f9fb18d68e1c7de92fcf17eb2a5874a93a17f0b2c46fa549805966fe233284
          name: container-image
